#!/usr/bin/env bash

# A short bash script to start the CNC test program
# It kills the PiGPIO server when the program exits,
# so that all servos will stop.
sudo pigpiod
python3 cnctest.py
sudo killall pigpiod
